AcademyAwardWinner:
  source: ''
  type: 'neighborhood'
  filename: 'avg_query_results/academy_award_winner.csv'
  metric: 'mean_squared_pairwise_distance'
  column:
      a: ''
      b: ''

Authors:
  source: ''
  type: 'neighborhood'
  filename: 'avg_query_results/academy_award_winner.csv'
  metric: 'mean_squared_pairwise_distance'
  column:
      a: ''
      b: ''

CanadaCitizen:
  source: ''
  type: 'neighborhood'
  filename: 'avg_query_results/academy_award_winner.csv'
  metric: 'mean_squared_pairwise_distance'
  column:
      a: ''
      b: ''

FootballPlayers:
  source: ''
  type: 'neighborhood'
  filename: 'avg_query_results/academy_award_winner.csv'
  metric: 'mean_squared_pairwise_distance'
  column:
      a: ''
      b: ''

GermanCitizen:
  source: ''
  type: 'neighborhood'
  filename: 'avg_query_results/academy_award_winner.csv'
  metric: 'mean_squared_pairwise_distance'
  column:
      a: ''
      b: ''

NobelPrizeHolders:
  source: ''
  type: 'neighborhood'
  filename: 'avg_query_results/academy_award_winner.csv'
  metric: 'mean_squared_pairwise_distance'
  column:
      a: ''
      b: ''
