version: 2

jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: Test
          command: pipenv run pytest

workflows:
  version: 2
  build:
    jobs:
      - test