version: 2

jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          name: Test
          command: pipenv run pytest
  pylint:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          name: Lint
          command: find . -iname "*.py" | xargs pipenv run pylint
  docs-build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          name: Build docs
          command: cd docs/ && pipenv run make html
      - persist_to_workspace:
          root: docs/_build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@example.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "89:38:8a:ca:be:0f:e3:f9:09:a6:26:8c:24:4c:59:8d"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html

workflows:
  version: 2
  build:
    jobs:
      - test
      - docs-build
      - pylint
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master