version: 2

jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          name: Test
          command: pipenv run pytest
  docs-build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html

workflows:
  version: 2
  build:
    jobs:
      - test